version: '3.5'

services:
  clear-score-aggregator-service:
    build:
      context: ./
      args:
        PROJECT: ${PROJECT}
    ports:
      - '${HTTP_PORT}:4000'
    volumes:
      - './.aws:/root/.aws'
      - '.:/${PROJECT}'
      - '/${PROJECT}/node_modules'
    environment:
      - AWS_PROFILE=clear-score
      - CSCARDS_ENDPOINT=${CSCARDS_ENDPOINT}
      - SCOREDCARDS_ENDPOINT=${SCOREDCARDS_ENDPOINT}
    entrypoint: top
    networks:
      - local
      - clear-score
    logging:
      driver: none
networks:
  local:
  clear-score:
    name: clear-score
    external: true
s